### ISSUE TITLE
組み込み関数envの実装

### ISSUE THREAD

**Issue by yuto1009** [yuto1009/minishell#4]

**Comment by yoshiddddd** [comment]
extern char **environ使うのはなし？？そしたら結構だるそう

**Comment by yuto1009** [comment]
> extern char **environ使うのはなし？？そしたら結構だるそう

ダメなのかな
あれもしかしてグローバル変数か

**Comment by yoshiddddd** [comment]
なんか他の人のコード参照しまくってみたんだが、どうやらローカル変数としてenvironは使ってるけど、これにプラスアルファして他の処理を付け加えている
今んとこenvironだけではダメな理由が見当たってないからもう少し調べますまだ時間かかりそうだ・・
